// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace eShop.DataBaseRepository.DB.Models
{
    public partial class Order
    {
        public Guid Id { get; set; }
        public byte OrderStatusId { get; set; }
        public Guid? UserId { get; set; }
        public Guid? UserAddressId { get; set; }
        public decimal TotalPrice { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime? DateChanged { get; set; }
        public DateTime? DateDeleted { get; set; }

        public virtual OrderStatus OrderStatus { get; set; }
        public virtual UserAddress UserAddress { get; set; }
    }
}