// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace eShop.DataBaseRepository.DB.Models
{
    public partial class User
    {
        public User()
        {
            UserAddresses = new HashSet<UserAddress>();
            UsersInRoles = new HashSet<UsersInRole>();
        }

        public Guid Id { get; set; }
        public Guid? SessionId { get; set; }
        public string ActivationDate { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime? DateChanged { get; set; }
        public DateTime? DateDeleted { get; set; }

        public virtual ICollection<UserAddress> UserAddresses { get; set; }
        public virtual ICollection<UsersInRole> UsersInRoles { get; set; }
    }
}